[colors]
# The default text color
foreground = "#c9d1d9"
# The default background color
background = "#0d1117"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#c9d1d9"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#0d1117"
# Specifies the border color of the cursor when the cursor style is set to Block,
# or the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#30363d"

# the foreground color of selected text
selection_fg = "#f0f6fc"
# the background color of selected text
selection_bg = "rgba(56,139,253,0.4)"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "#161b22"

# The color of the split lines between panes
split = "#30363d"

ansi = [
  "#484f58",
  "#ff7b72",
  "#3fb950",
  "#d29922",
  "#58a6ff",
  "#bc8cff",
  "#39c5cf",
  "#b1bac4"
]
brights = [
  "#6e7681",
  "#ffa198",
  "#56d364",
  "#e3b341",
  "#79c0ff",
  "#d2a8ff",
  "#56d4dd",
  "#f0f6fc"
]

# Arbitrary colors of the palette in the range from 16 to 255
indexed = {   136 = "#f0883e",   137 = "#f778ba",   138 = "#F78166" }

# Since: nightly builds only
# When the IME, a dead key or a leader key are being processed and are effectively
# holding input pending the result of input composition, change the cursor
# to this color to give a visual cue about the compose state.
compose_cursor = "#f0883e"

